"""One set per language that ships a Snowball stemmer.

Each query reaches its memory only through a different inflection of a word the
memory holds, and every such word is more than the typo stage's edit budget
away from the word the memory spells. `inflection_check.py` verifies both
properties and `inflection.py` measures the set on the strict pass alone.

The memories are written in the language, and the store is told so through the
settings the way a person's would be. The keys of `MEMORIES` are local to a
language.
"""

SETS = {
    "es": dict(
        language="Spanish",
        memories={
            "busqueda": ("La migración de la búsqueda a Meilisearch",
                "Elasticsearch costaba demasiado para un índice pequeño. Meilisearch tolera errores tipográficos y la latencia bajó a quince milisegundos. Medimos cuánto tarda la reindexación completa: cuatro minutos."),
            "cron": ("Corregimos el cron de conciliación bancaria que se ejecutaba dos veces",
                "Dos réplicas del worker tenían el planificador activo. Ahora el cron toma un bloqueo asesor de Postgres antes de empezar y la réplica que no lo obtiene termina sin hacer nada."),
            "indice": ("Los índices parciales evitan escanear los pedidos archivados",
                "Creamos un índice parcial solo para los pedidos activos. El plan de consulta dejó de recorrer la tabla entera y la consulta bajó de dos segundos a veinte milisegundos."),
            "fuga": ("Fuga de memoria: los marcadores del mapa no se liberaban",
                "Cada vez que el usuario movía el mapa se creaban marcadores nuevos y nadie liberaba los anteriores. Ahora el componente libera los marcadores al desmontarse y la memoria se mantiene estable."),
            "cobros": ("Cobros duplicados al reintentar el pago desde la app",
                "Los reintentos del móvil creaban cobros duplicados. Ahora los pagos exigen una clave de idempotencia y guardamos la respuesta veinticuatro horas."),
            "traducciones": ("Traducciones y plurales en la web",
                "Los textos sueltos no admitían plurales. Pasamos todas las traducciones a mensajes con formato ICU y el equipo de localización revisa las cadenas nuevas cada semana."),
            "version": ("Los usuarios seguían en la versión vieja después del despliegue",
                "La caché del navegador servía el paquete anterior. Añadimos un hash al nombre del archivo y el servicio de actualización avisa cuando hay una versión nueva."),
            "redondeo": ("Redondeo de importes en las facturas",
                "Los importes se redondeaban por línea y la suma de las facturas no cuadraba con el total. Ahora usamos enteros en céntimos y redondeamos una sola vez al final."),
        },
        queries=[
            ("cuánto tarda reindexar la búsqueda completa", "busqueda"),
            ("el cron se ejecutó dos veces", "cron"),
            ("crear un índice parcial", "indice"),
            ("liberación de los marcadores del mapa", "fuga"),
            ("duplicar cobros al reintentar el pago", "cobros"),
            ("localizar las cadenas nuevas", "traducciones"),
            ("actualizar versión nueva", "version"),
            ("redondeando importes de las facturas", "redondeo"),
        ],
    ),
    "pt": dict(
        language="Portuguese",
        memories={
            "busca": ("A migração da busca para o Meilisearch",
                "O Elasticsearch custava caro para um índice pequeno. O Meilisearch tolera erros de digitação e a latência caiu para quinze milissegundos. Medimos quanto tempo leva a reindexação completa: quatro minutos."),
            "cron": ("Corrigimos o cron de conciliação bancária que rodava duas vezes",
                "Duas réplicas do worker estavam com o agendador ativo. Agora o cron pega um bloqueio consultivo do Postgres antes de começar e a réplica que não o consegue termina sem fazer nada."),
            "indice": ("Índices parciais evitam varrer os pedidos arquivados",
                "Criamos um índice parcial só para os pedidos ativos. O plano de consulta parou de percorrer a tabela inteira e a consulta caiu de dois segundos para vinte milissegundos."),
            "vazamento": ("Vazamento de memória: os marcadores do mapa não eram liberados",
                "Toda vez que o usuário mexia no mapa eram criados marcadores novos e ninguém soltava nenhum dos anteriores. Agora o componente solta os marcadores ao ser desmontado e a memória fica estável."),
            "cobrancas": ("Cobranças duplicadas ao repetir o pagamento pelo app",
                "As novas tentativas do celular criavam cobranças duplicadas. Agora os pagamentos exigem uma chave de idempotência e guardamos a resposta por vinte e quatro horas."),
            "traducoes": ("Traduções e plurais no site",
                "Os textos soltos não aceitavam plurais. Passamos todas as traduções para mensagens com formato ICU e a equipe de localização revisa as strings novas toda semana."),
            "versao": ("Usuários continuavam na versão antiga depois da implantação",
                "O cache do navegador entregava o pacote anterior. Adicionamos um hash ao nome do arquivo e o serviço de atualização avisa quando há uma versão nova."),
            "arredondamento": ("Arredondamento dos valores nas faturas",
                "Os valores eram arredondados por linha e a soma das faturas não batia com o total. Agora usamos inteiros em centavos e arredondamos uma única vez no final."),
        },
        queries=[
            ("reindexar a busca completa", "busca"),
            ("o cron rodou duas vezes", "cron"),
            ("criar índice parcial para pedidos", "indice"),
            ("liberação dos marcadores do mapa", "vazamento"),
            ("duplicar cobranças ao repetir pagamento", "cobrancas"),
            ("localizar as strings novas", "traducoes"),
            ("atualizar versão nova", "versao"),
            ("arredondar valores das faturas", "arredondamento"),
        ],
    ),
    "fr": dict(
        language="French",
        memories={
            "recherche": ("La migration de la recherche vers Meilisearch",
                "Elasticsearch coûtait trop cher pour un petit index. Meilisearch tolère les fautes de frappe et la latence est tombée à quinze millisecondes. Nous avons mesuré la durée de la réindexation complète : quatre minutes."),
            "cron": ("Correction du cron de rapprochement bancaire qui s'exécutait deux fois",
                "Deux réplicas du worker avaient le planificateur actif. Désormais le cron prend un verrou consultatif Postgres avant de démarrer et la réplica qui ne l'obtient pas s'arrête sans rien faire."),
            "index": ("Les index partiels évitent de parcourir des commandes archivées",
                "Nous avons ajouté un index partiel seulement pour les commandes actives. Le plan de requête ne parcourt plus toute la table et la requête est tombée de deux secondes à vingt millisecondes."),
            "fuite": ("Fuite mémoire : les marqueurs de la carte n'étaient pas libérés",
                "Chaque fois que l'utilisateur déplaçait la carte, de nouveaux marqueurs apparaissaient et personne ne supprimait les précédents. Maintenant le composant supprime les marqueurs au démontage et la mémoire reste stable, ce qui évite de garder des marqueurs inutiles."),
            "paiements": ("Paiements en double lors d'une nouvelle tentative depuis l'appli",
                "Les nouvelles tentatives du mobile créaient des paiements en double. Désormais les paiements exigent une clé d'idempotence et nous gardons la réponse vingt-quatre heures."),
            "traductions": ("Traductions et pluriels sur le site",
                "Les textes isolés n'acceptaient pas les pluriels. Nous avons converti toutes les traductions en messages au format ICU et l'équipe de localisation relit les nouvelles chaînes chaque semaine."),
            "version": ("Les utilisateurs restaient sur l'ancienne version après le déploiement",
                "Le cache du navigateur servait l'ancien paquet. Nous avons ajouté un hash au nom du fichier et le service de mise à jour prévient quand une nouvelle version est disponible."),
            "arrondi": ("Arrondi des montants dans les factures",
                "Les montants étaient arrondis par ligne et la somme des factures ne correspondait pas au total. Nous utilisons maintenant des entiers en centimes et nous arrondissons une seule fois à la fin."),
        },
        queries=[
            ("Meilisearch tolérait les fautes de frappe", "recherche"),
            ("le cron s'exécute deux fois", "cron"),
            ("la requête tombait à vingt millisecondes", "index"),
            ("gardait des marqueurs inutiles", "fuite"),
            ("créer des paiements en double", "paiements"),
            ("accepter les pluriels", "traductions"),
            ("déployer nouvelle version", "version"),
            ("arrondissement des montants", "arrondi"),
        ],
    ),
    "de": dict(
        language="German",
        memories={
            "webhooks": ("Eingehende Webhooks sicher verarbeiten",
                "Eingehende Webhooks konnten gefälscht werden. Wir müssen jeden Aufruf mit einer HMAC-Signatur prüfen, bevor wir ihn verarbeiten. Abgelehnte Aufrufe landen im Fehlerlog, der Rest geht an den Worker."),
            "abgleich": ("Doppelte Bankabgleiche durch zwei Worker",
                "Zwei Replikate des Workers hatten den Scheduler aktiv. Jetzt müssen sich die Replikate vor dem Start verbinden und eine Sperre in Postgres holen; wer sie nicht bekommt, beendet sich."),
            "teilindex": ("Teilindex für aktive Bestellungen",
                "Wir wollen alte Bestellungen nicht mehr scannen. Die Abfrage ist jetzt schnell, von zwei Sekunden auf zwanzig Millisekunden, und das mit einem Teilindex."),
            "speicherleck": ("Speicherleck bei den Markierungen der Karte",
                "Beim Verschieben der Karte entstanden neue Markierungen, und niemand wollte die alten entfernen. Jetzt muss die Komponente alle Markierungen beim Schließen der Karte freigeben."),
            "zahlung": ("Doppelte Abbuchungen bei erneutem Senden der Zahlung",
                "Wiederholte Anfragen der App führten zu doppelten Abbuchungen. Wir müssen Zahlungen jetzt wiederholen können, ohne doppelt zu belasten: Jede Anfrage trägt einen Idempotenz-Schlüssel."),
            "texte": ("Mehrzahlformen auf der Webseite",
                "Die losen Texte kannten keine Plurale. Wir wollen alle Texte in ICU-Nachrichten übersetzen, und das Team der Lokalisierung prüft die Zeichenketten jede Woche."),
            "version": ("Nutzer sahen nach dem Rollout noch die alte Version",
                "Der Browser-Cache lieferte das alte Paket aus. Wir müssen den Dateinamen mit einem Hash versehen und beim Rollout den Dienst neu einrichten, damit eine neue Version erkannt wird."),
            "rundung": ("Rundung der Beträge in Rechnungen",
                "Beträge wurden pro Zeile gerundet, und die Summe der Rechnungen passte nicht zum Gesamtbetrag. Jetzt wollen wir ganze Cent-Beträge verwenden und nur einmal am Ende runden."),
        },
        queries=[
            ("Verarbeitungen der Webhooks", "webhooks"),
            ("Verbindungen vor dem Start", "abgleich"),
            ("schnellere Abfrage mit Teilindex", "teilindex"),
            ("Entfernungen der Karte", "speicherleck"),
            ("Wiederholungen der Zahlung", "zahlung"),
            ("Übersetzungen der Zeichenketten", "texte"),
            ("Einrichtungen beim Rollout", "version"),
            ("Verwendungen der Beträge", "rundung"),
        ],
    ),
    "it": dict(
        language="Italian",
        memories={
            "ricerca": ("La migrazione della ricerca a Meilisearch",
                "Elasticsearch costava troppo per un indice piccolo. Meilisearch tollera gli errori di battitura e la latenza è scesa a quindici millisecondi. Abbiamo misurato quanto dura la reindicizzazione completa: quattro minuti."),
            "cron": ("Il cron della riconciliazione bancaria girava due volte",
                "Due repliche del worker avevano lo scheduler attivo. Ora il cron prende un lock consultivo di Postgres prima di partire e la replica che non lo ottiene termina senza fare nulla."),
            "indici": ("Gli indici parziali evitano di scansionare gli ordini archiviati",
                "Abbiamo aggiunto un indice parziale solo per gli ordini attivi. Il piano della query non percorre più l'intera tabella e la query è scesa da due secondi a venti millisecondi."),
            "perdita": ("Perdita di memoria: i marcatori della mappa non venivano rilasciati",
                "Ogni volta che l'utente spostava la mappa venivano generati nuovi marcatori e nessuno rimuoveva i precedenti. Ora il componente rimuove i marcatori allo smontaggio e la memoria resta stabile."),
            "addebiti": ("Addebiti doppi quando l'app ritenta il pagamento",
                "I tentativi dal telefono creavano addebiti doppi. Ora i pagamenti richiedono una chiave di idempotenza e conserviamo la risposta per ventiquattro ore."),
            "traduzioni": ("Traduzioni e plurali nel sito",
                "I testi sparsi non accettavano i plurali. Abbiamo spostato tutte le traduzioni in messaggi con formato ICU e il team di localizzazione rivede le stringhe nuove ogni settimana."),
            "versione": ("Gli utenti restavano sulla versione vecchia dopo il rilascio",
                "La cache del browser serviva il pacchetto precedente. Abbiamo aggiunto un hash al nome del file e il servizio di aggiornamento avvisa quando c'è una versione nuova."),
            "arrotondamento": ("Arrotondamento degli importi nelle fatture",
                "Gli importi venivano arrotondati per riga e la somma delle fatture non tornava con il totale. Ora usiamo interi in centesimi e arrotondiamo una sola volta alla fine."),
        },
        queries=[
            ("reindicizzare la ricerca completa", "ricerca"),
            ("il cron gira due volte", "cron"),
            ("archiviazione ordini attivi", "indici"),
            ("spostamento della mappa", "perdita"),
            ("creare addebiti doppi", "addebiti"),
            ("localizzare le stringhe nuove", "traduzioni"),
            ("aggiornare la versione nuova", "versione"),
            ("arrotondando gli importi delle fatture", "arrotondamento"),
        ],
    ),
    "ro": dict(
        language="Romanian",
        memories={
            "cautare": ("Migrarea căutării produselor la Meilisearch",
                "Elasticsearch costa prea mult pentru un index mic. Meilisearch tolerează greșeli de scriere, iar latența a scăzut la cincisprezece milisecunde. Reindexarea completă durează patru minute."),
            "cron": ("Cron-ul de reconciliere bancară rula de două ori",
                "Două replici ale worker-ului aveau planificatorul activ. Acum cron-ul ia un lock în Postgres înainte de a porni, iar replica care nu îl obține se oprește fără să facă nimic."),
            "index": ("Index parțial în loc de scanarea întregii tabele",
                "Am adăugat un index parțial doar pentru comenzi active. Planul interogării nu mai parcurge toată tabela, iar interogarea a scăzut de la două secunde la douăzeci de milisecunde."),
            "scurgere": ("Scurgere de memorie: marcatori ai hărții nu erau eliberați",
                "De fiecare dată când utilizatorul muta harta se creau marcatori noi și nimeni nu elibera pe cei vechi. Acum componenta șterge marcatorii la demontare și memoria rămâne stabilă."),
            "plati": ("Plăți duble când aplicația trimite din nou cererea",
                "Cererile repetate de pe telefon creau plăți duble. Acum cererile au o cheie de idempotență și păstrăm răspunsul douăzeci și patru de ore."),
            "traduceri": ("Traduceri și plural pe site",
                "Textele izolate nu acceptau plural. Am mutat toate traducerile în mesaje cu format ICU, iar echipa de localizare verifică șirurile noi în fiecare săptămână."),
            "versiune": ("Utilizatorii rămâneau pe versiunea veche după lansare",
                "Cache-ul browserului servea pachetul vechi. Am adăugat un hash în numele fișierului, iar serviciul de actualizare anunță când există o versiune nouă."),
            "rotunjire": ("Rotunjire în facturi",
                "Sumele erau rotunjite pe rând, iar totalul facturi nu se potrivea cu suma finală. Acum folosim întregi în bani mici și rotunjim o singură dată la final."),
        },
        queries=[
            ("greșelilor de scriere Meilisearch", "cautare"),
            ("replicilor worker-ului", "cron"),
            ("index parțial comenzilor active", "index"),
            ("scurgere marcatorilor hărții", "scurgere"),
            ("plăților duble", "plati"),
            ("mesajelor cu format ICU", "traduceri"),
            ("versiunilor vechi", "versiune"),
            ("sumele facturilor", "rotunjire"),
        ],
    ),
    "nl": dict(
        language="Dutch",
        memories={
            "zoek": ("De migratie van de zoekfunctie naar Meilisearch",
                "Elasticsearch was te duur voor een kleine index. Meilisearch vergeeft typefouten en de latentie daalde naar vijftien milliseconden. We hebben gemeten hoe lang het volledig herindexeren duurt: vier minuten."),
            "cron": ("De cron voor de bankafstemming draaide twee keer",
                "Twee replica's van de worker hadden de planner actief. Nu moet de cron vóór de start verbinden met Postgres en een lock nemen; wie die niet krijgt, stopt zonder iets te doen."),
            "index": ("Een gedeeltelijke index voorkomt het scannen van gearchiveerde bestellingen",
                "Om niet alle bestellingen te scannen willen we een gedeeltelijke index beperken tot actieve bestellingen. Het queryplan hoeft de hele tabel niet meer af te lopen, en de query daalde van twee seconden naar twintig milliseconden."),
            "geheugenlek": ("Geheugenlek: de markeringen van de kaart werden niet vrijgegeven",
                "Elke keer dat de gebruiker de kaart verschoof, ontstonden nieuwe markeringen en niemand gaf de oude vrij. Nu moet de component alle markeringen bij het verwerken van het ontkoppelen vrijgeven."),
            "betalingen": ("Dubbele afschrijvingen bij opnieuw proberen vanuit de app",
                "Herhaalde verzoeken van de telefoon maakten dubbele afschrijvingen. Nu moeten we transacties kunnen herhalen zonder dubbel te belasten: elk verzoek draagt een idempotentiesleutel."),
            "teksten": ("Meervoudsvormen op de website",
                "De losse teksten kenden geen meervoud. We gaan alle teksten vertalen naar ICU-berichten, en het lokalisatieteam controleert elke week de nieuwe tekenreeksen."),
            "versie": ("Gebruikers bleven op de oude versie na de uitrol",
                "De browsercache leverde het oude pakket. We hebben een hash aan de bestandsnaam toegevoegd en de updateservice meldt wanneer er een nieuwe versie is, zodra we het pakket wijzigen."),
            "bedragen": ("Bedragen op facturen klopten niet",
                "Bedragen werden per regel afgerond en de som van de facturen klopte niet met het totaal. Nu gebruiken we gehele centen en willen we maar één keer afronden aan het einde."),
        },
        queries=[
            ("herindexeringen van de zoekfunctie", "zoek"),
            ("verbindingen met Postgres", "cron"),
            ("beperkingen gedeeltelijke index", "index"),
            ("verwerkingen van de kaart", "geheugenlek"),
            ("herhalingen van transacties", "betalingen"),
            ("vertalingen nieuwe tekenreeksen", "teksten"),
            ("wijzigingen nieuwe versie", "versie"),
            ("afrondingen van bedragen", "bedragen"),
        ],
    ),
    "sv": dict(
        language="Swedish",
        memories={
            "sokning": ("Migrering av sökningen till Meilisearch",
                "Elasticsearch var för dyrt för ett litet index. Meilisearch förlåter stavfel och latensen sjönk till femton millisekunder. Vi mätte hur länge en fullständig omindexering tar: fyra minuter."),
            "cron": ("Cronjobbet för bankavstämning kördes två gånger",
                "Två repliker av workern hade schemaläggaren aktiv. Nu tar cronjobbet ett lås i Postgres innan start, och repliken som inte får det avslutas utan att göra något."),
            "index": ("Partiellt index undviker att skanna arkiverade beställningar",
                "Vi lade till ett partiellt index bara för aktiva beställningar. Frågeplanet går inte längre igenom varje tabell, och frågan gick från två sekunder till tjugo millisekunder."),
            "markor": ("Minnesläcka: kartans markör släpptes aldrig",
                "Varje gång användaren flyttade kartan skapades en ny markör och ingen släppte den gamla. Nu släpper komponenten markör när kartan tas bort och minnet håller sig stabilt."),
            "debitering": ("Dubbla debiteringar när appen försöker igen",
                "Nya försök från mobilen skapade dubbla debiteringar. Nu kräver varje betalning en idempotensnyckel och vi sparar svaret i tjugofyra timmar."),
            "oversattning": ("Översättning och plural på webben",
                "De lösa texterna saknade plural. Vi flyttade all översättning till ICU-meddelanden och lokaliseringsteamet granskar nya strängar varje vecka."),
            "version": ("Användare satt kvar på den gamla utgåvan efter utrullningen",
                "Webbläsarens cache levererade det gamla paketet. Vi la till en hash i filnamnet och tjänsten för uppdatering meddelar när det finns en ny version."),
            "avrundning": ("Avrundning av belopp på fakturor",
                "Belopp avrundades per rad och summan av fakturorna stämde inte med totalen. Nu använder vi heltal i ören och gör en enda avrundning i slutet."),
        },
        queries=[
            ("migreringarna av sökningen", "sokning"),
            ("låsen i Postgres", "cron"),
            ("tabellerna för aktiva beställningar", "index"),
            ("markörerna när kartan tas bort", "markor"),
            ("betalningarna dubbla debiteringar", "debitering"),
            ("översättningarna nya strängar", "oversattning"),
            ("versionerna efter utrullningen", "version"),
            ("avrundningarna av belopp", "avrundning"),
        ],
    ),
    "ca": dict(
        language="Catalan",
        memories={
            "cerca": ("La migració de la cerca a Meilisearch",
                "Elasticsearch costava massa per a una base petita. Meilisearch tolera errors tipogràfics i la latència va baixar a quinze mil·lisegons. Hem mesurat quant tarda la reindexació completa: quatre minuts."),
            "cron": ("El cron de conciliació bancària s'executava dues vegades",
                "Dues rèpliques del worker tenien el planificador actiu. Ara el cron pren un bloqueig consultiu de Postgres abans de començar i la rèplica que no l'obté acaba sense fer res. Vam afegir una repetició segura per si el procés cau."),
            "index": ("Indexació parcial per no escanejar els pedidos arxivats",
                "Hem limitat la indexació als pedidos actius i els arxivats ja no es toquen. El pla de consulta va deixar de recórrer la taula sencera i la consulta va baixar de dos segons a vint mil·lisegons."),
            "fuga": ("Fuga de memòria: els marcadors del mapa no s'alliberaven",
                "Cada vegada que l'usuari movia el mapa es creaven marcadors nous i ningú feia l'alliberament dels anteriors. Ara el component fa l'alliberament dels marcadors en desmuntar-se i la memòria es manté estable."),
            "cobros": ("La duplicació de cobraments al reintentar el pagament des de l'app",
                "Al reintentar el pagament des de l'app, es creava una duplicació de cobraments i en alguns casos es cobrava dues vegades. Ara els pagaments exigeixen una clau d'idempotència i guardem la resposta vint-i-quatre hores."),
            "traduccions": ("Traduccions i plurals a la web",
                "Els textos solts no admetien plurals. Vam passar totes les traduccions a missatges amb format ICU i l'equip de localització revisa les cadenes noves cada setmana."),
            "version": ("Els usuaris seguien en la versió vella després del desplegament",
                "La caché del navegador servia el paquet anterior. Vam afegir un hash al nom del fitxer i el servei d'actualització avisa quan hi ha una versió nova."),
            "redondeo": ("L'arrodoniment dels imports a les factures",
                "L'arrodoniment es feia per línia i la suma de les factures no quadrava amb el total. Ara fem servir enters en cèntims i l'arrodoniment es fa una sola vegada al final, i els imports queden exactes."),
        },
        queries=[
            ("quant tarda reindexar la cerca completa", "cerca"),
            ("repetir el cron dues vegades", "cron"),
            ("indexar els pedidos actius", "index"),
            ("alliberar els marcadors del mapa", "fuga"),
            ("duplicar cobraments en reintentar el pagament", "cobros"),
            ("localitzar les cadenes noves", "traduccions"),
            ("actualitzar la versió nova", "version"),
            ("arrodonir els imports de les factures", "redondeo"),
        ],
    ),
    "eu": dict(
        language="Basque",
        memories={
            "bilaketa": ("Bilaketaren migrazioa Meilisearch-era",
                "Elasticsearch garestiegia zen indize txiki batentzat. Meilisearch-ek dokumentuak azkar aurkitzen ditu eta bilaketa azkarra eskaintzen du. Latentzia hamabost milisegundora jaitsi zen eta bilaketa osoak lau minutu behar ditu oraindik."),
            "cron": ("Banku-kontziliazioko cron-a bi aldiz exekutatu zen",
                "Worker-aren bi erreplikek planifikatzailea aktibo zuten. Orain cron-ak Postgres-en blokeo aholkuemailea hartzen du hasi aurretik, eta lortzen ez duen erreplika ezer egin gabe amaitzen da. Konpondu genuen hori asteazkenean."),
            "index": ("Indize partziala artxibatutako eskaerak eskaneatzea saihesten du",
                "Eskaera aktiboetarako indize partziala txertatu genuen. Kontsulta-planak ez du jada taula osoa zeharkatzen, eta kontsulta bi segundotatik hogei milisegundora jaitsi zen."),
            "memoria": ("Memoria-isuria: maparen markatzaileak ez ziren askatzen",
                "Erabiltzaileak mapa mugitzen zuen bakoitzean markatzaile berriak sortzen ziren eta inork ez zituen zaharrak askatu. Orain osagaiak markatzaileak askatzen ditu kentzean, eta memoria egonkor mantentzen da."),
            "kobrantza": ("Kobrantza bikoitzak aplikaziotik berriro saiatzean",
                "Telefonotik egindako saiakerek kobrantza bikoitzak sortzen zituzten. Orain ordaindu aurretik idempotentzia-gakoa eskatzen dugu eta erantzuna hogeita lau orduz gordetzen dugu."),
            "itzulpen": ("Itzulpenak eta pluralak webgunean",
                "Testu solteek ez zituzten pluralak onartzen. Itzulpen guztiak ICU formatuko mezutara eraman genituen eta kate berriak lokalizatu genituen astero."),
            "bertsio": ("Erabiltzaileek bertsio zaharra zuten hedapenaren ondoren",
                "Nabigatzailearen cacheak pakete zaharra zerbitzatzen zuen. Fitxategiaren izenari hash bat gehitu genion eta eguneratze-zerbitzuak bertsio berria dagoela ohartarazten du. Paketea berritu behar da."),
            "faktura": ("Fakturetako zenbatekoak ez zetozen bat",
                "Zenbatekoak lerroka biribildu ziren eta fakturen baturak ez zuen bat egiten guztizkoarekin. Orain zentimoetan osoko zenbakiak erabiltzen ditugu eta amaieran behin bakarrik biribildu."),
        },
        queries=[
            ("aurkikuntza azkarra bilaketa", "bilaketa"),
            ("konponketa cron-ak bi aldiz", "cron"),
            ("txertaketa indize partziala", "index"),
            ("askapena markatzaileak maparen", "memoria"),
            ("ordainketa bikoitzak aplikaziotik", "kobrantza"),
            ("lokalizazioa kate berriak", "itzulpen"),
            ("berrikuntza bertsio zaharra", "bertsio"),
            ("biribilketa zenbatekoak fakturetako", "faktura"),
        ],
    ),
    "pl": dict(
        language="Polish",
        memories={
            "wyszukiwanie": ("Wyszukiwanie przenieśliśmy do Meilisearch",
                "Elasticsearch był za drogi dla małej bazy. Meilisearch toleruje literówki, a opóźnienie spadło w ciągu piętnastu milisekund. Zmierzyliśmy, ile trwa pełne przenoszenie: cztery minuty."),
            "cron": ("Zadanie crona od uzgadniania bankowego uruchamiało się dwa razy",
                "Dwie repliki workera miały aktywny harmonogram. Teraz zadanie crona bierze blokadę doradczą Postgresa przed startem, a replika, która jej nie dostanie, kończy się bez niczego."),
            "indeks": ("Indeks częściowy zamiast skanowania całej tabeli",
                "Dodaliśmy indeks częściowy tylko dla aktywnych zamówień. Plan zapytania nie przechodzi już całej tabeli, a zapytanie spadło z dwóch sekund do dwudziestu milisekund."),
            "pamiec": ("Wyciek pamięci: znaczniki mapy nie były zwalniane",
                "Za każdym razem, gdy użytkownik przesuwał mapę, powstawały nowe znaczniki i nikt nie zwalniał starych. Teraz komponent zwalnia znaczniki przy odmontowaniu, a pamięć pozostaje stabilna."),
            "platnosc": ("Płatność pobierana dwa razy przy ponownej próbie z aplikacji",
                "Ponowne próby z telefonu tworzyły podwójne płatności. Teraz każda płatność wymaga klucza idempotencji i zachowujemy odpowiedź przez dwadzieścia cztery godziny."),
            "tlumaczenie": ("Tłumaczenie i liczba mnoga w serwisie",
                "Luźne teksty nie obsługiwały liczby mnogiej. Przenieśliśmy całe tłumaczenie do komunikatów w formacie ICU, a zespół lokalizacji sprawdza nowe ciągi co tydzień."),
            "wdrozenie": ("Wdrożenie nowej wersji nie dotarło do użytkowników",
                "Pamięć podręczna przeglądarki serwowała stary pakiet. Dodaliśmy hash do nazwy pliku, a usługa aktualizacji informuje, gdy jest nowa wersja."),
            "zaokraglenie": ("Zaokrąglenie kwot na fakturach",
                "Zaokrąglenie robiliśmy wiersz po wierszu i suma faktur nie zgadzała się z totalem. Teraz używamy liczb całkowitych w groszach i zaokrąglenie robimy tylko raz na końcu."),
        },
        queries=[
            ("wyszukiwaniami w Meilisearch", "wyszukiwanie"),
            ("zadaniami crona dwa razy", "cron"),
            ("indeksami aktywnych zamówień", "indeks"),
            ("pamięciami znaczniki mapy", "pamiec"),
            ("płatnościami z aplikacji", "platnosc"),
            ("tłumaczeniami nowe ciągi", "tlumaczenie"),
            ("wdrożeniami nowej wersji", "wdrozenie"),
            ("zaokrągleniami kwot na fakturach", "zaokraglenie"),
        ],
    ),
}
